### ISSUE TITLE
Impossible to build the project on Xcode 7.2 with Carthage

### ISSUE THREAD

**Issue by CallMeSH** [danthorpe/Money#41] opened 2016-03-04 11:25 UTC
This cartfile 

`github "danthorpe/Money" ~>  1.6.0`

With Carthage 0.12.0 and Xcode 7.2.1 produces this output:

```
$ carthage update Money --platform iOS
*** Fetching Money
*** Fetching ValueCoding
*** Checking out Money at "1.6.0"
*** Checking out ValueCoding at "1.2.0"
*** xcodebuild output can be found in /var/folders/mf/0kc1sz9n17s12drx20lnkh7r0000gn/T/carthage-xcodebuild.YN4lFV.log
*** Building scheme "ValueCoding-iOS" in ValueCoding.xcodeproj
*** Building scheme "Money-iOS" in Money.xcodeproj
*** Building scheme "Money" in Custom Money.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(1 failure)
<unknown>:0: error: no such file or directory: '/Users/user/Documents/Xcode Projects/project/Carthage/Checkouts/Money/Money/Shared/FX/Bitcoin.swift'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(1 failure)

```

I hope this will help. :smile:

**Comment by danthorpe** [comment] 2016-03-04 12:05
Thanks - I've fixed this in another project of mine yesterday. Will take care of it today.

The issue, is that now Carthage builds all Xcode projects that it finds. I typically put example projects in the same repo - but they configure their dependencies using CocoaPods (because it's possible to reference local dependencies) - and so Carthage fails to build them....

**Comment by dlo** [comment] 2016-03-10 19:39
I'm running into a similar issue with Carthage as of today. Not sure if your fixes for the previous issue have already been applied or not:

```
*** Fetching Money
*** Fetching ValueCoding
*** Checking out ValueCoding at "1.2.0"
*** Checking out Money at "1.6.0"
*** xcodebuild output can be found in /var/folders/2y/314v5wvn6v92078kg6mmg7hw0000gn/T/carthage-xcodebuild.fJX7l3.log
*** Building scheme "ValueCoding-tvOS" in ValueCoding.xcodeproj
*** Building scheme "ValueCoding-iOS" in ValueCoding.xcodeproj
*** Building scheme "ValueCoding-OSX" in ValueCoding.xcodeproj
*** Building scheme "ValueCoding-watchOS" in ValueCoding.xcodeproj
*** Building scheme "Money-iOS" in Money.xcodeproj
*** Building scheme "Money-OSX" in Money.xcodeproj
*** Building scheme "Money-watchOS" in Money.xcodeproj
*** Building scheme "Money-tvOS" in Money.xcodeproj
*** Building scheme "Money" in Custom Money.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Headers/Money-Swift.h /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money-Swift.h
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Headers/Money-Swift.h /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money-Swift.h
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm.swiftdoc /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money.swiftdoc
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm.swiftmodule /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money.swiftmodule
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm64.swiftmodule /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money.swiftmodule
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm64.swiftdoc /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money.swiftdoc
	Ld /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money normal arm64
	Ld /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money normal armv7
	CreateUniversalBinary /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Money normal armv7\ arm64
	GenerateDSYMFile /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework.dSYM /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Money
(12 failures)
ld: warning: linking against dylib not safe for use in application extensions: /Users/dan/Documents/Projects/Call Smart/Carthage/Checkouts/Money/Carthage/Build/watchOS/ValueCoding.framework/ValueCoding
ld: warning: linking against dylib not safe for use in application extensions: /Users/dan/Documents/Projects/Call Smart/Carthage/Checkouts/Money/Carthage/Build/watchOS/ValueCoding.framework/ValueCoding
ld: warning: linking against dylib not safe for use in application extensions: /Users/dan/Documents/Projects/Call Smart/Carthage/Checkouts/Money/Carthage/Build/tvOS/ValueCoding.framework/ValueCoding
ld: warning: linking against dylib not safe for use in application extensions: /Users/dan/Documents/Projects/Call Smart/Carthage/Checkouts/Money/Carthage/Build/tvOS/ValueCoding.framework/ValueCoding
<unknown>:0: error: no such file or directory: '/Users/dan/Documents/Projects/Call Smart/Carthage/Checkouts/Money/Money/Shared/FX/Bitcoin.swift'
<unknown>:0: error: no such file or directory: '/Users/dan/Documents/Projects/Call Smart/Carthage/Checkouts/Money/Money/Shared/FX/Bitcoin.swift'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money (No such file or directory)
error: cannot parse the debug map for "/Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Money": No such file or directory
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Headers/Money-Swift.h /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money-Swift.h
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Headers/Money-Swift.h /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money-Swift.h
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm.swiftdoc /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money.swiftdoc
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm.swiftmodule /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money.swiftmodule
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm64.swiftmodule /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money.swiftmodule
	Ditto /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Modules/Money.swiftmodule/arm64.swiftdoc /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money.swiftdoc
	Ld /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/arm64/Money normal arm64
	Ld /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Intermediates/Pods.build/Release-iphoneos/Money.build/Objects-normal/armv7/Money normal armv7
	CreateUniversalBinary /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Money normal armv7\ arm64
	GenerateDSYMFile /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework.dSYM /Users/dan/Library/Developer/Xcode/DerivedData/Custom_Money-cssttdahawlapucxrhpkndbdctpw/Build/Products/Release-iphoneos/Money.framework/Money
(12 failures)
```

**Comment by danthorpe** [comment] 2016-03-10 21:36
This has now been fixed on [`master`](https://github.com/danthorpe/Money/releases/tag/1.6.1), as version 1.6.1.

So, should all work without problems with Carthage now. Thanks for reporting this everyone!

**Comment by danthorpe** [comment] 2016-03-10 21:59
Just confirmed that this is fixed now. Please re-open if you have issues with 1.6.1!

**Closed by danthorpe** 2016-03-10 21:59 UTC
Labels: fixed

**Comment by dlo** [comment] 2016-03-10 22:33
Thanks!
